### ISSUE TITLE
Multi-world time tracking

### ISSUE THREAD

**Issue by hyperdefined** [hyperdefined/TimeBar#48]
Instead of having one main world to track time, a user requested the ability to track time in multiple worlds.

Simplify config maybe with this feature?

```yaml
# Set which worlds track time and which worlds show that time.
worlds:
  world:
    - world_nether
    - world__the_end
  world2:
    - world2_nether
    - world2_the_end
 ```
