### ISSUE TITLE
Colors not working for realistic season addon

### ISSUE THREAD

**Issue by TomcatHD** [hyperdefined/TimeBar#63]
colors:
  SPRING: "PINK"
  SUMMER: "YELLOW"
  FALL: "RED"
  WINTER: "BLUE"
  
  none of those colors are working for the SEASON placeholder.

**Comment by hyperdefined** [comment]
It works for me fine on a fresh new server. What is your RealisticSeasons version? Can you show me your `plugins/TimeBar/realisticseasons.yml` config?

Not sure if it's a copy & paste issue, but your colors section should be indented like this:
```yaml
colors:
  SPRING: "PINK"
  SUMMER: "YELLOW"
  FALL: "RED"
  WINTER: "BLUE"
```
